#!/bin/sh
#shopt -s extglob

error_exit()
{
    echo "$1" 1>&2
    exit 1
}

# Check if commit message argument
if [ -z "$1" ]
then
  echo "deploy script error: What changes did you make? Type a commit message."
  exit 1
fi

# Build successfuly or exit
stack clean
stack build || error_exit "deploy script error: Build failed"

# Push changes on hakyll branch to github
git add -A
git commit -m "$1" || error_exit "deploy script error: no changes to commit"
git push origin hakyll

# Switch to master branch
git checkout master

# delete old site
rm -rf *
#find . \! \( -name ".*" -or -name "CNAME" -or -name "README.md" \) -delete # XXX will delete git files
git add -A && git commit -m "delete old site"

# switch to hakyll branch and rebuild website
git checkout hakyll
stack exec blog rebuild

# switch to master, extract site and push
git checkout master
mv _site/* .
git add -A && git commit --amend -m "$1"
git push origin master

# rsync with remote wwwroot
rm -rf _site
rm -rf _cache
rsync -av * nbrk@linklevel.net:~/nbrk.linklevel.net.wwwroot

# return to original branch
git checkout hakyll
